### PR TITLE
Update to PostCSS 6

### LINKED ISSUE #1: Which versions of Node do you intend to support?
I see you have [tests](https://github.com/MattDiMu/postcss-replace-overflow-wrap/blob/master/.travis.yml) for Node v5, v4, and v0.12. The current LTS is v6. I would recommend you support this one and take advantage of [function bodies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Function_body) and [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters).

You could be doubly safe and support LTS v4, but I would highly recommend dropping support for v0.12.

To understand the difference in feature sets between v6, v4, and v0.12, please see: https://kangax.github.io/compat-table/es6/#node65

### LINKED ISSUE #2: Unnecessary walkRules
You seem to be doing some unnecessary walking on [line 8](https://github.com/MattDiMu/postcss-replace-overflow-wrap/blob/master/index.js#L8), as you are ultimately walking declarations on [line 9](https://github.com/MattDiMu/postcss-replace-overflow-wrap/blob/master/index.js#L9).

I would recommend reducing these to:

```js
css.walkDecls('overflow-wrap', /* your code */)
```

### PR DESCRIPTION
**Pull request by jonathantneal**
Hi @MattDiMu, this PR comes with a few changes, separated by commits:

- Changes from https://github.com/MattDiMu/postcss-replace-overflow-wrap/pull/3 (resolves #2)
- Updates to PostCSS v6
- Updates to Node 4x syntax (resolves #1)
- Whitelists index.js vs ignoring other files
- Removes unused vars
- Updates CHANGELOG and bumps package.json

You would then need to run `npm publish` and you’d be all set.

### CODE REVIEW

**Comment by Semigradsky** [comment]
@MattDiMu ping

**Comment by jonathantneal** [comment]
@MattDiMu ping

**Comment by jonathantneal** [comment]
Would you mind granting us privileges to accept this PR?

**Comment by MattDiMu** [comment]
Sorry for the delay, couldn't do any open source work lately, will look at this pr in the evening.

**Comment by MattDiMu** [comment]
Took embarrassingly long, but now it should work fine. Thx a lot for the work.

**Pull request merged**
